version: '3'

services:
  worker:
    build: ./worker
    ports:
      - 8000:8000
    depends_on:
      - redisdb
      - postgresdb
    env_file:
      - .env
  
  postgresdb:
    restart: always
    image: postgres:alpine
    env_file:
      - .env
    ports: 
      - 5678:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  redisdb:
    restart: always
    image: redis:alpine
    ports:
      - 6378:6379
    env_file:
      - .env
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
  
